# Generated by Django 5.1.2 on 2024-11-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_shippingaddress_order_shipping_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping addresses'},
        ),
    ]
