# Generated by Django 5.1.2 on 2024-11-05 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_orderitem_price_paid_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 1, 50, 45, 284778)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
