# Generated by Django 5.1.2 on 2024-11-05 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_order_date_ordered_alter_orderitem_price_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 3, 26, 41, 292159)),
        ),
    ]
