# Generated by Django 5.1.2 on 2024-11-05 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_paid',
            new_name='price_paid_per_unit',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 3, 27, 5, 102474)),
        ),
    ]
